### ISSUE TITLE
关于paper的问题

### ISSUE THREAD

**Issue by windyear** [wxkpythonwork/Reinforcement-Learning#1]
请问这个仓库复现的是哪个paper的实验呢？ @wxkpythonwork

**Comment by wxkpythonwork** [comment]
在写论文的部分代码，在投递还没发。。

**Comment by windyear** [comment]
哦哦，正好在做有关反向散射的问题，方便加个qq交流下吗？ @wxkpythonwork

**Comment by wxkpythonwork** [comment]
q980948564

**Comment by windyear** [comment]
@wxkpythonwork 麻烦通过一下验证，十万火急
